### ISSUE TITLE
Restore fails with "failed to check s3 bucket" error

### ISSUE THREAD

**Issue by laurie-kepford** [rancher/backup-restore-operator#203]
I am trying to restore a backup to a new cluster. Using instructions here: https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/.  Restore is failing with this error:

```
INFO[2022/03/20 16:50:50] invoking set s3 service client                s3-accessKey="base64encodedaccess key=" s3-bucketName=mybucket s3-endpoint=s3.us-west-2.amazonaws.com s3-endpoint-ca= s3-folder= s3-region=us-west-2
ERRO[2022/03/20 16:50:50] error syncing 'restore-migration': handler restore: failed to check s3 bucket:mybucket, err:400 Bad Request, requeuing
```

Backups are in an s3 bucket. I have verified that I am using the same credentials that were used to create the backup,  And the path to the backup is correct.  What else could be wrong?

**Comment by superseb** [comment]
What version was and is used (if they are different)?

Also please share the exact config used (redacted) and I assume Amazon S3 is used as storage.

**Comment by laurie-kepford** [comment]
The old Rancher is a **docker install, Version 2.6.2.** The new Cluster is a **EKS cluster, K8s 1.20.**  Yes, S3 is used for storage.  I did not install rancher on the new cluster.

It's not a large installation, only one downstream cluster.
What would happen if I did the following:

- Install rancher on the new cluster.
- Remove rancher from the downstream cluster
- Import the downstream cluster into the new rancher?

What would be the down side of doing it that way?  What kinds of things would I likely loose and have to re-create?

My Config for creating the restore:

```
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-migration
spec:
  backupFilename: nightly-65eff810-5027-4527-b0ab-81ac234768f0-2022-03-20T00-00-00Z.tar.gz
  prune: false
  storageLocation:
    s3:
      credentialSecretName: s3-creds
      credentialSecretNamespace: default
      bucketName: rancher-backups
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
```
S3 Secret

```
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  accessKey: ACCESSKEYBASE64ENCODED
  secretKey: SECRETKEYBASE64ENCODED
```

**Comment by laurie-kepford** [comment]
On the new cluster, I installed the backup but using the following command.

```
helm repo add rancher-charts https://charts.rancher.io
helm repo update
helm install rancher-backup-crd rancher-charts/rancher-backup-crd -n cattle-resources-system --create-namespace --version 2.1.0
helm install rancher-backup rancher-charts/rancher-backup -n cattle-resources-system --version 2.1.0
```
On the old cluster I had installed it through the ui
![2022-03-25 at 9 33 AM](https://user-images.githubusercontent.com/86793511/160162503-53d9474d-67ef-4f2e-97c1-7ea555114e38.png)

**Comment by superseb** [comment]
And the bucket and the credentials are 100% identical? Were you able to restore from it on the original setup? Seems very weird to have a difference in exactly the same code with exactly the same configuration.

**Comment by superseb** [comment]
Yes, I tracked it down to https://github.com/rancher/docs/pull/3594. It was generically changed to base64-encoded values but it wasn't taken into account that it depends on using `data` or `stringData`.

**Comment by laurie-kepford** [comment]
With the fix of the credentials I got a little further. But I still think something is missing. I am now getting this error:
I```
NFO[2022/03/31 13:58:29] Processing Restore CR restore-migration
INFO[2022/03/31 13:58:29] Restoring from backup rch2/nightly-backup-file.tar.gz
INFO[2022/03/31 13:58:29] invoking set s3 service client                s3-accessKey=REDACTED s3-bucketName=my-rancher-backups s3-endpoint=s3.us-west-2.amazonaws.com s3-endpoint-ca= s3-folder= s3-region=us-west-2
INFO[2022/03/31 13:58:29] Temporary location of backup file from s3: /tmp/nightly-vetpro-65eff810-5027-4527-b0ab-81ac234768f0-2022-03-31T00-00-00Z.tar.gz
INFO[2022/03/31 13:58:29] Successfully downloaded [rch2/nightly-backup-file.tar.gz]
INFO[2022/03/31 13:58:30] Processing controllerRef apps/v1/deployments/rancher
WARN[2022/03/31 13:58:30] Error getting object for controllerRef rancher, skipping it
INFO[2022/03/31 13:58:30] Starting to restore CRDs for restore CR restore-migration
INFO[2022/03/31 13:58:30] restoreResource: Restoring apprevisions.project.cattle.io of type apiextensions.k8s.io/v1, Resource=customresourcedefinitions
INFO[2022/03/31 13:58:30] Processing controllerRef apps/v1/deployments/rancher
WARN[2022/03/31 13:58:30] Error getting object for controllerRef rancher, skipping it
ERRO[2022/03/31 13:58:30] Error restoring CRDs restoreCRDs: restoreResource: err updating resource CustomResourceDefinition.apiextensions.k8s.io "apprevisions.project.cattle.io" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]
ERRO[2022/03/31 13:58:30] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing
```

**Comment by laurie-kepford** [comment]
Don't know if it matters but my source cluster is running Rancher 2.6.1

**Comment by superseb** [comment]
This is the same as https://github.com/rancher/backup-restore-operator/issues/186, was the original cluster where the backup was taken upgraded (both k8s and rancher) in its lifetime?

**Comment by laurie-kepford** [comment]
Yes it was.

I looked at that article.  But I don't understand how to fix it.  There is a command listed there but the person says "i have no idea if this breaks anything".  Plus it does not specify where to run it?  Do I execute inside the docker container?

Or would it be sufficient to uninstall backup from source cluster and re-install it?

**Comment by laurie-kepford** [comment]
Thanks!!

**Comment by superseb** [comment]
Updates will be in https://github.com/rancher/backup-restore-operator/issues/186, this issue remains open to validate https://github.com/rancher/backup-restore-operator/pull/204

**Comment by superseb** [comment]
### Root cause
Errors were unclear regarding S3 operations, although the original issue is followed up on by the docs team (incorrect way of creating secrets), the logging was not very clear either. The PR should make it more clear

### What was fixed, or what changes have occurred
- Ability to configure `-debug` or `-trace` to the deployment so you can configure debug or trace log level. 
- S3 secret logging, when providing a wrong/incomplete/badly structured secret, the logging should indicate what is wrong
- Added filename and bucket to info and error log lines for context

### Areas or cases that should be tested

Just regular cases should show the new logging, and when s3 secret is incorrectly structured (no `accessKey` or no `secretKey` for example)
 
### What areas could experience regressions?
Nothing specific as it's all logs only 

### Are the repro steps accurate/minimal?
- Add `-debug` or `-trace` to the deployment and it should log its setting the configured level
- Create a badly structured s3 secret and check the logs

**Comment by laurie-kepford** [comment]
I upgraded to the newest version.  Now I am getting this error on the restore:  As you can see it now downloads the backup, but the restores still fails.
```
INFO[2022/05/01 15:26:50] Temporary location of backup file from s3: /tmp/nightly-vetpro-65eff810-5027-4527-b0ab-81ac234768f0-2022-05-01T00-00-00Z.tar.gz
INFO[2022/05/01 15:26:50] Successfully downloaded [nightly-vetpro-65eff810-5027-4527-b0ab-81ac234768f0-2022-05-01T00-00-00Z.tar.gz]
INFO[2022/05/01 15:26:51] Processing controllerRef apps/v1/deployments/rancher
WARN[2022/05/01 15:26:51] Error getting object for controllerRef rancher, skipping it
INFO[2022/05/01 15:26:51] Starting to restore CRDs for restore CR restore-migration
INFO[2022/05/01 15:26:51] restoreResource: Restoring resourcesets.resources.cattle.io of type apiextensions.k8s.io/v1, Resource=customresourcedefinitions
INFO[2022/05/01 15:26:51] Successfully restored resourcesets.resources.cattle.io
INFO[2022/05/01 15:26:51] restoreResource: Restoring projectnetworkpolicies.management.cattle.io of type apiextensions.k8s.io/v1, Resource=customresourcedefinitions
INFO[2022/05/01 15:26:51] Processing controllerRef apps/v1/deployments/rancher
WARN[2022/05/01 15:26:51] Error getting object for controllerRef rancher, skipping it
ERRO[2022/05/01 15:26:51] Error restoring CRDs restoreCRDs: restoreResource: err updating resource CustomResourceDefinition.apiextensions.k8s.io "projectnetworkpolicies.management.cattle.io" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]
ERRO[2022/05/01 15:26:51] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing
```

**Comment by superseb** [comment]
For the `preserveUnknownFields` fix (https://github.com/rancher/backup-restore-operator/issues/186), you will need to install v2.1.2 RC currently as there is no official release with the fix yet.

**Comment by laurie-kepford** [comment]
v2.1.2 RC of the backup-operator?

**Comment by superseb** [comment]
Yes, v2.1.2 will be released with Rancher v2.6.5 but if you want to use it now, you have to use an RC version of the backup-restore-operator. Here is the latest RC: https://github.com/rancher/backup-restore-operator/releases/tag/v2.1.2-rc3

**Comment by MSpencer87** [comment]
_Verified on v2.6.5-rc6_

Steps to Reproduce:

1. Bring up HA Rancher v2.6.5-rc6 and Install Rancher Backups 2.1.0
2. Create resources (user, cluster templates etc)
3. Create s3 backup
4. Create new cluster, Bring up HA Rancher v2.6.5-rc6 and Install Rancher Backups 2.1.0
5. Restore from s3 backup (No errors)

**Comment by laurie-kepford** [comment]
I am not able to update my production rancher to 2.5.6-rc.  Two reasons:  1. there is a company rule against using beta/rc products in production. 2. There is a known bug in upgrading the docker version of rancher.  I tried to do it some months ago using the workaround that was suggested, but rancher failed to come up afterwards.  So I am now in the process of building a brand new HA Rancher 2.6.4.  When its ready I will move my apps over there.

**Comment by kphunter** [comment]
I had trouble connecting to S3 by following the docs - turns out it was an issue with the way the secret was created. After creating a [generic secret using literals](https://github.com/stashed/stash/issues/547#issuecomment-411355399), it worked.
